# Copyright (C) 2023 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"

  commands:
    - docs/setup_build_env_rtd.sh
    - CC=clang CXX=clang++ pip install . -v
    - make -C docs linkcheck html latexpdf
    - mkdir -p "$READTHEDOCS_OUTPUT/pdf"
    - cp -r docs/_build/html "$READTHEDOCS_OUTPUT/"
    - cp docs/_build/latex/hictkpy.pdf "$READTHEDOCS_OUTPUT/pdf/"

formats:
  - pdf
