# Copyright (C) 2023 Roberto Rossini <roberros@uio.no>
#
# SPDX-License-Identifier: MIT

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  commands:
    - sudo apt-get update
    - sudo apt-get install -y ca-certificates lsb-release curl
    - curl -LO "https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb"
    - sudo apt-get install -y *.deb
    - rm *.deb
    - sudo apt-get update
    - sudo apt-get install -y libarrow-dev libboost-dev libdeflate-dev libhdf5-dev libzstd-dev
    - pip install 'conan>=2'
    - docs/update_conan_config_rtd.py conanfile.py
    - pip install -r docs/requirements.txt
    - pip install . -v
    - docs/update_index_links.py --root-dir "$PWD" --inplace
    - make -C docs linkcheck
    - make -C docs html
    - make -C docs latexpdf
    - mkdir -p "$READTHEDOCS_OUTPUT/pdf"
    - cp -r docs/_build/html "$READTHEDOCS_OUTPUT/"
    - cp docs/_build/latex/hictkpy.pdf "$READTHEDOCS_OUTPUT/pdf/"

formats:
  - pdf
